### ISSUE TITLE
The phrase 'region' seems to be missing from scrubbed 'county_parish' names.

### ISSUE THREAD

**Issue by phylosaurus** [ojalaquellueva/gnrs#17]
The phrase 'region' seems to be missing from scrubbed 'county_parish' names.
Example:
Canada, British Columbia, Fraser-Fort George
![Screenshot 2024-07-30 at 6 44 42 PM](https://github.com/user-attachments/assets/292b593e-98e8-4f9d-9adc-05da39066df6)

The the query returns "al District of Fraser-Fort George" but the correct name is "Regional District of Fraser-Fort George".

**Comment by ojalaquellueva** [comment]
Fixed. GNRS now returns "Fraser-Fort George" as the county_parish value. All county level political divisions with prefix "Regional District of" or suffix "Regional District" are not correctly represented in the GNRS by their base names only.

Note that the GNRS stores the base name of the political division only, and removes class names such as "State", "Provincia de", "County" and "Regional District". If you want to have the GNRS return the base name plus class name, if any (e.g., "Regional District of Fraser-Fort George") then please add this behavior as a new "Feature request' issue.

**Comment by phylosaurus** [comment]
Hi Brad,

The issue persists - I've tried both the R package and the web interface
and get the following:

"al District of East Kootenay"
"al District of Central Okanagan"
"al District of Nanaimo"
"al District of Okanagan-Similkameen"

for queries like "CA, British Columbia, East Kootenay"

Another weird result:
"Canada, British Columbia, Cowichan Valley" returns "Cowichan Valley
Regional".
Similarly, see:
"Columbia-Shuswap Regional"
"Capital Regional"

Also GNRS returns things that are not wrong per se, but have class names
attached, like:
"Fairbanks North Star Borough"
"Rural Municipality of Portage la Prairie"
"Valdez-Cordova Census Area"
"Northwest Arctic Borough"
"United Counties of Leeds and Grenville"
"Kodiak Island Borough"
"District Municipality of Muskoka"

Not sure if all of these are intentional. Sorry for the email - I got my
git password wrong too many times and am locked out for a bit.

Cheers,

Dan

**Comment by ojalaquellueva** [comment]
@phylosaurus  Dan, regarding these examples:

> Also GNRS returns things that are not wrong per se, but have class names attached, like: 
"Fairbanks North Star Borough" 
"Rural Municipality of Portage la Prairie" 
"Valdez-Cordova Census Area" 
"Northwest Arctic Borough" 
"United Counties of Leeds and Grenville" 
"Kodiak Island Borough" 
"District Municipality of Muskoka"

These are different variants of the same general bug. Why? Because they are different class names. Each class name requires its own custom WHEN [...] THEN [...] clause in a very large CASE statement in a monster UPDATE query that breaks up concatenated political division names into base names and class names. Furthermore, compound class names containing prepositions (e.g., "District Municipality of") must be parsed before pure compound class names  (e.g., "District Municipality"), which in turn must be parsed before atomic class names (e.g., "District" and "Municipality") to avoid leaving behind orphan words and strings in the base name (e.g., "of Muskoka" or "al District of Fraser-Fort George").

Please add country and state/province to the above political division and resubmit in a comment below and I'll add them to the monster query. This time I promise to clear the cache...
